#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Bab\Console\Command\GetCommand;
use Bab\Console\Command\PublishCommand;

$application = new Application();
$application->add(new GetCommand);
$application->add(new PublishCommand);
$application->run();
